### ISSUE TITLE
Release Swift 4.2 version to Cocoapods 

### ISSUE THREAD

**Issue by mjrehder** [dmrschmidt/DSWaveformImage#10]
I have another open source project on github which uses DSWaveformImage and I would like to submit that pod to CocoaPods with Swift 4.2 changes. However, I cannot do that until this library is released to CocoaPods as well (Current version 5.0.x is only Swift 4.0)

**Comment by dmitryond** [comment]
Try 

`pod 'DSWaveformImage', :git => 'https://github.com/dmrschmidt/DSWaveformImage.git', :commit => '01c6cdbb3025b8bfa3a9bd266f7da9a436185605'`

in podfile

**Comment by mjrehder** [comment]
I have no issues with taking a particular commit or version from Github. I can always make a fork if I need something specific.
My issue is that you cannot specify a non-released version in the .podspec file (Not the Podfile!).
The .podspec file of my own pod is verified and used when I attempt to release to cocoapods and then this fails.
Is there an issue with the current Swift 4.2 version so that you cannot release it to cocoapods using 'pod trunk push DSWaveformImage.podspec' ?

**Comment by dmrschmidt** [comment]
Sorry for the late response. No issue with it whatsoever, I just hadn't done it and I keep never noticing github notifications about my repos. I'm on this now.

**Comment by dmrschmidt** [comment]
For what it's worth, pushed a cocoapods update now as 5.1.2.
