### ISSUE TITLE
Application crashes because of memory issue while creating waveform.

### ISSUE THREAD

**Issue by dmitryond** [dmrschmidt/DSWaveformImage#11]
This code in AudioProcessor.swift: 
```
            if let sampleBuffer = trackOutput.copyNextSampleBuffer(),
                let blockBuffer = CMSampleBufferGetDataBuffer(sampleBuffer) {
                let blockBufferLength = CMBlockBufferGetDataLength(blockBuffer)
                let sampleLength = CMSampleBufferGetNumSamples(sampleBuffer) * channelCount(from: assetReader)
                var data = Data(capacity: blockBufferLength)
                data.withUnsafeMutableBytes { (blockSamples: UnsafeMutablePointer<Int16>) in
                    CMBlockBufferCopyDataBytes(blockBuffer, atOffset: 0, dataLength: blockBufferLength, destination: blockSamples)
                    CMSampleBufferInvalidate(sampleBuffer)

                    let processedSamples = process(blockSamples,
                                                   ofLength: sampleLength,
                                                   from: assetReader,
                                                   downsampledTo: targetSampleCount)
                    outputSamples += processedSamples
                }
            }
```
ends up crashing the application when selected asset is long enough. In my tests, audio file is 13 minutes long. Crash happens while over 500MB of memory is used in the while loop. If the block buffer isn't set crash doesn't happen.

**Comment by dmrschmidt** [comment]
@dmitryond could you please provide me with the audio file you are using and a stack trace?

**Comment by dmitryond** [comment]
Here's the link to the file, it's m4a.

https://we.tl/t-kkXCKdjWCh

I was using the library on iPhone 6 app.

The workaround I am currently using is converting the audio file to caf format real quick before making waveform. :)

**Comment by dmrschmidt** [comment]
Thanks. Just did a quick check and can see the memory usage spike. Interesting as I did a test with a 2h file and it worked, no problem. Your track seems to behave differently.

I'll keep investigating and hopefully find enough time to have a fix in the next few days.

**Comment by dmitryond** [comment]
I agree, it is strange. I didn't care enough to dive deeper into this, but since converting the same track to another format "fixes" the bug, I just assume there is either additional audio track or other info that inflates the memory taken by each individual sample.

**Comment by dmrschmidt** [comment]
Good instinct. It's in the reading of metadata to get the number of audio channels. That's highly inefficient code as I am now realizing. Will work on a fix soon.

**Comment by dmrschmidt** [comment]
This should be fixed now. I'm seeing another issue with this track, but that's related to #8 I think and long tracks not getting rendered correctly (if at all). Working on that separately.
