### ISSUE TITLE
erminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan 0; 0 0]'

### ISSUE THREAD

**Issue by AbySwifter** [dmrschmidt/DSWaveformImage#13]
this is an error， when init view. 
![屏幕快照 2019-08-27 下午1 08 09](https://user-images.githubusercontent.com/18734693/63742556-c2956e00-c8cb-11e9-806a-116b138de206.png)

**Comment by dmrschmidt** [comment]
I somehow never get the notifications from github when new issues are files. Could you provide a little more details how this happened? Ideally what the `WaveformConfiguration` looks like and some info about the `Waveform``s `AVURLAsset`.

**Comment by dmrschmidt** [comment]
closed due to inactivity + I wasn't able to reproduce. Feel free to re-open with more details.
