### ISSUE TITLE
Load a Remote URL

### ISSUE THREAD

**Issue by daihovey** [dmrschmidt/DSWaveformImage#22]
Has anyone attempted to build a version which could load a remote URL?
`AVAssetReader` complains currently `"Cannot initialize an instance of AVAssetReader with an asset at non-local URL"`

**Comment by dmrschmidt** [comment]
I've never actually tried that myself tbh. But you can simply download the file with `URLSession`. Code for this (just an illustration as it ignores all sorts of possible error scenarios) could look like this:

```swift
let task = URLSession.shared.downloadTask(with: remoteAudioURL) { downloadedURL, urlResponse, error in
    guard let downloadedURL = downloadedURL else { return }

    let cachesFolderURL = try? FileManager.default.url(for: .cachesDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
    let audioFileURL = cachesFolderURL!.appendingPathComponent("yourLocalAudioFile.m4a")
    try? FileManager.default.copyItem(at: downloadedURL, to: audioFileURL)

    DispatchQueue.main.async {
        self.WaveformView.waveformAudioURL = audioFileURL
    }
}
task.resume()
```

**Comment by sanketk2020** [comment]
Hi @dmrschmidt ,
I tried your suggested code, and I also try from my side by downloading the audio file and saving it locally and then assign the URL to WaveformView but I get no results.
I get this error : ERROR loading asset / audio track

Is there any other way to generate the wave from the URL?

Thanks
