### ISSUE TITLE
Crop audio

### ISSUE THREAD

**Issue by rastaman111** [dmrschmidt/DSWaveformImage#25]
Hey @dmrschmidt!  Do you have the ability to cut a fragment from a finished file?  That is, select start and finish as RangeSlider

**Comment by dmrschmidt** [comment]
Currently this is not something that's supported by the library itself, no. So you'd need to create a temporary audio file yourself at the moment, wich you trim to the desired range. Depending on your use case it might be - but most likely isn't - acceptable to instead crop the resulting image.

With regards to supporting this use case from within the library directly, I don't think I'll be able to add this in anytime soon. I could see it as a useful addition though, so if you come up with a workable solution, I'd be more than happy to merge a PR :)

**Comment by rastaman111** [comment]
> Currently this is not something that's supported by the library itself, no. So you'd need to create a temporary audio file yourself at the moment, wich you trim to the desired range. Depending on your use case it might be - but most likely isn't - acceptable to instead crop the resulting image.
> 
> 
> 
> With regards to supporting this use case from within the library directly, I don't think I'll be able to add this in anytime soon. I could see it as a useful addition though, so if you come up with a workable solution, I'd be more than happy to merge a PR :)

Yes, I know that you need to create a temporary file with the desired interval, there is nothing complicated here, there is a solution.  But I can't find a ready-made good solution for RangeSlider specifically for audio files, although there are solutions from the video ...

**Comment by dmrschmidt** [comment]
Hey @rastaman111, I'm sorry but I'm not quite sure I understand what RangeSlider, and what video you are referring to. As far as I am aware, there is no RangeSlider native to UIKit or SwiftUI, so I assume you must be referring to another 3rd party library?

Regarding a workable solution to the original problem, you've problem come across this answer to [how to slice an audio file within a `CMTimeRange`](https://stackoverflow.com/a/68598028/580730). (Haven't tested that myself but it looks pretty legit).

**Comment by rastaman111** [comment]
That's what I mean [rangeSlider](https://github.com/WorldDownTown/RangeSeekSlider).  That is, on your Waveline, move the sliders and select the range

**Comment by dmrschmidt** [comment]
OK, so yeah. That [stackoverflow answer](https://stackoverflow.com/a/68598028/580730) should do the trick for you or at the very least guide you into the right direction then. You'd just need to map that rangeSlider's selected min and max value to the [CMTimeRange](https://developer.apple.com/documentation/coremedia/cmtimerange-qts)'s desired values.
