### ISSUE TITLE
Can you provide an example for SwiftUI?

### ISSUE THREAD

**Issue by williamrodz** [dmrschmidt/DSWaveformImage#26]
I am trying to use the WaveformLiveView in **SwiftUI**, but am having a hard time since there is no direct example.

How can I incorporate these elements into a declarative SwiftUI view definition? The following fails due to a `Static method 'buildBlock' requires that 'WaveformLiveView' conform to 'View'` error 
```
   var body: some View {
        NavigationView {
            VStack{
                WaveformLiveView(configuration: Waveform.Configuration(dampening: .init(percentage: 0.125, sides: .both)))
```

**Comment by dmrschmidt** [comment]
Hey @williamrodz I'll try to incorporate a SwiftUI example soon into the example app. Not sure when I'll get to that, but maybe not yet this weekend. Bridging UIKit views into SwiftUI is fortunately mostly quite straightforward though. You'll want to [have a look at `UIViewRepresentable`](https://developer.apple.com/documentation/swiftui/uiviewrepresentable) for that.

There's a [simple writeup on Hacking with Swift](https://www.hackingwithswift.com/quick-start/swiftui/how-to-wrap-a-custom-uiview-for-swiftui) on how to use it in a basic example. You should get a basic starting point by just replacing `UITextView ` in their example with `WaveformLiveView`'s constructor. Let me know if this helps :)

**Comment by dmrschmidt** [comment]
Better late than never, I've added a SwiftUI example now to the example app in the repo. You can try it out in Xcode.

The most important component here is [WaveformImageViewUI](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImageExample/SwiftUIExample/WaveformImageViewUI.swift) as the SwiftUI wrapper.
