### ISSUE TITLE
Support clear background

### ISSUE THREAD

**Issue by vburojevic** [dmrschmidt/DSWaveformImage#27]
If the background color config is set to clear, the waveform background is black.

I see that [this commit](https://github.com/dmrschmidt/DSWaveformImage/commit/a9d010c2e3b7faf5db00ec3cc2890e6369ba4e96) a few years back fixed that, but I guess it got broken again since the drawing logic uses a different API now.

is it possible to have a clear background with this version?

**Comment by dmrschmidt** [comment]
Hey @vburojevic,

are you sure the black background isn't set by anything else? If I run the current example app, the backgrounds of the top and bottom views there are transparent, in fact.

see [the README screenshot taken directly from the app](https://github.com/dmrschmidt/DSWaveformImage/blob/main/screenshot.png)

**Comment by vburojevic** [comment]
@dmrschmidt yes, you're correct, I guess it has black background because I put it in an `UIStackView`, for some reason. But that's not an issue with this lib I think, so closing.

Thanks and sorry for reporting an issue with the lib since it wasn't!

**Comment by dmrschmidt** [comment]
No worries at all, I'm always here to try and help :)
