### ISSUE TITLE
XCFramework with SPM support

### ISSUE THREAD

**Issue by illiniChief6** [dmrschmidt/DSWaveformImage#29]
Hi, I love using this library on iOS! It makes audio visualizations so cool!  

Is there a plan to make this library support xcframeworks with SPM? This way this library will compile on M1 Macs simulators and run with Mac Catalyst?

Thanks!

**Comment by dmrschmidt** [comment]
Hey illiniChief6, thanks for reaching out.

Good suggestion to support Catalyst as well. I have never looked into Catalyst, so I don't really know the culprits.

That said, the library is already available via SPM as an xcframework, see https://github.com/dmrschmidt/DSWaveformImage#installation.

Under "Deployment Info" in the frameworks build target settings, Mac Catalyst is also actually already checked (see image).
<img width="954" alt="Screenshot 2022-03-03 at 09 22 47" src="https://user-images.githubusercontent.com/69365/156484069-9f29f50a-9128-4fba-b965-a814d2648f2d.png">

So naïvely I'd have assumed "it just works". I can have a look at it some time over the next week. Is there a good sample app code you could point me to where I can give this a try? I'll just google for one, but asking in case there's other specificities I'm not aware of that may or may not apply to all Catalyst apps.

**Comment by dmrschmidt** [comment]
I just tried it out in the included sample app. All I had to do was enable Mac Catalyst via the checkbox (see above commit) and run it.

<img width="901" alt="Screenshot 2022-03-03 at 09 31 57" src="https://user-images.githubusercontent.com/69365/156485304-db2a2a3d-eff9-49ad-812c-75f07856892e.png">

So it should work for you as well with the version that had already been out (I did not need to release a new version, so 9.0.3 is still the latest).

Please let me know if this does or does not work for you, so I can have another look in case I'm missing something :)
