### ISSUE TITLE
Creating Waves Visualisation from recording within view fram

### ISSUE THREAD

**Issue by dhimansham** [dmrschmidt/DSWaveformImage#31]
**Here is what I am trying to do:**

![Wave Expected Gif][1]

**The screenshot is taken from a XR iPhone.**

![Wave Done Gif][2]

I have been working in AVAudioPlayer and I would like to draw a waveform which looks like the first gif. I am using [DSWaveformImage-main](https://github.com/dmrschmidt/DSWaveformImage) Github pods to draw waves when the user records the sound. But I'm confused how to draw waves in the view frame without automatically scrolling and not going outside from the view. Means when the user records the sound the waves automatically will draw on the view, but not move outside, i need to show all the waves within the  view frame and shrink the waves if it goes outside the frame.

**Question:** How to show the draw waves in the view frame without goes to outside from the view?

Can someone please explain to me how to draw same, I've tried to draw these waves with the above pods code but no results yet.

Any help would be greatly appreciated.

Thanks in advance.

  [1]: https://i.stack.imgur.com/42wEO.gif
  [2]: https://i.stack.imgur.com/E99NC.gif

**Comment by dhimansham** [comment]
Hello @dmrschmidt,  Thank you for your reply. 

I'm just using your code, download the code and run on the simulator. So I don't have any my code.

Yes, I have checked the iOS example app. I'm using your code which returned me the above results. And i want to fit the waveform graph onto the screen. Is it possible with your code?

please guide me, how to achieve this, if you need any other information please let me know I will try to my best. 

Thanks

**Comment by dmrschmidt** [comment]
Ah, if my above assumption about the dB value being reported back by AVAudioRecorder is correct, when you run the app and look at the logs, you should see output like this:

<img width="263" alt="Screenshot 2022-03-31 at 16 13 22" src="https://user-images.githubusercontent.com/69365/161078465-b88da25f-2ea9-4dd6-9de7-ab73f876c922.png">

Only that there would be values sporadically that are greater than 0. The typical expected range in those prints would be always negative and negative values will always fit into the view bounds (with 0 being exactly the view height).

**Comment by dhimansham** [comment]
> Just to be clear: are you talking about vertical or horizontal fit?

horizontal fit

Ok, I understand your point. We need pre-recorded audio file for horizontal fit. Is it not possible without pre-recorded audio file or available on disk / the network. Currently,  We need to show the waves and fit the waveform graph onto the screen when user record the audio.

**Comment by dmrschmidt** [comment]
OK, gotcha. So yeah, in that case - right now - you *could* - in theory - use [WaveformImageDrawer.waveformImage(from samples: [Float], with configuration: Waveform.Configuration)](https://github.com/dmrschmidt/DSWaveformImage/blob/main/DSWaveformImage/DSWaveformImage/WaveformImageDrawer.swift#L51), which returns a `UIImage`.

That would be horrendously performance and memory inefficient though. I think it should ultimately be not too trivial to make a different `WaveformLiveView`, but unfortunately it's not recorded out of the box with that rendering behavior you desire.

I'll put this on my list of features to add. Can't guarantee I'll get to this anytime soon though.

**Comment by dmrschmidt** [comment]
Having thought about this a little bit more, it would - in fact - not be that straight forward.

The problem for this requirement is, that the samples coming in, will need to be downsampled on the fly to always fit the window. The more samples you get over time, the more crucial performance becomes, so this would need to be taken care of from the start.

In theory, all the required logic / math bits are there. But I'd want this to come with a more structured refactoring of the way the processing is handled right now. The `WaveformAnalyzer`, which right now can only read from its internal `AVAssetReader` would need to instead read from some kind of `DataSource` protocol or whatnot.

So I'd say from my side - for now - this is a #wontfix simply out of personal time constraints.

I'd really love to do this though - in fact, my own app would benefit from this - so there's still a chance I'll get to it at some point.
