### ISSUE TITLE
WaveFormImageDrawer.swift  - Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by narcodog** [dmrschmidt/DSWaveformImage#33]
In WaveFormImageDrawer.swift, in the function drawGraph, for the line:

    let colors = NSArray(array: colors.map(\.cgColor)) as CFArray
    
 I get the error "Type of expression is ambiguous without more context" 

"\.cgColor" is underlined.

Xcode 11.2.1 (The most recent version I can use on my current machine)

**Comment by narcodog** [comment]
Great, I'm no longer getting the error :)

Thanks for the speedy reply :)

**Comment by dmrschmidt** [comment]
Glad I could help :) Just merged this change back into main and released it as 10.0.1. So you can use that version now instead of the branch.
