### ISSUE TITLE
Is there a way to zoom and scroll waveform?

### ISSUE THREAD

**Issue by ldakhoa** [dmrschmidt/DSWaveformImage#37]
Hi @dmrschmidt, Do you have the ability to zoom in/out the waveform and scroll it?

**Comment by dmrschmidt** [comment]
Hey @ldakhoa,

this is not something that's currently supported natively.

If there is no real-time interaction requirement, and you know the beginning and ending boundaries rather statically, you could [slice the audio file beforehand](https://github.com/dmrschmidt/DSWaveformImage/issues/25#issuecomment-970529487) and then just pass that into the waveformview.

I'm assuming you're looking for a real-time dragging supported zoom though, to which the answer for now is just an unfortunate "no, sorry".

**Comment by ldakhoa** [comment]
Hey, thank you for your answer
