### ISSUE TITLE
Generate the wave from URL.

### ISSUE THREAD

**Issue by sanketk2020** [dmrschmidt/DSWaveformImage#39]
Hello,

I tried by downloading the audio file and saving it locally and then assign the URL to WaveformView but I get no results.

I get this error : ERROR loading asset / audio track

Is there any other way to generate the wave from the URL?

Thanks

**Comment by dmrschmidt** [comment]
Does the file play normally in an AVPlayer? That message typically comes up when the media format is not supported for instance.

Is the URL for the file you’re trying to use publicly available? If so, could you paste it here? I could try and have a look myself then.

**Comment by dmrschmidt** [comment]
Also, did you have a look at this scaffolded example for downloading a remote URL? https://github.com/dmrschmidt/DSWaveformImage/issues/22#issuecomment-787943864

**Comment by dmrschmidt** [comment]
Closed due to inactivity. Feel free to re-open if this is still an issue.

**Comment by sanketk2020** [comment]
Yes, the file plays normally in an AVPlayer but I had an issue with accessing the URL;
 before I access the URL like this 
 
``` URL(string: "XYZ") ```
 
 but then I realize and change the way of accessing the URL like this 

```URL(fileURLWithPath: audioPath)```

and this way works like charm.

Anyways thanks for the reply.

**Comment by dmrschmidt** [comment]
I'm glad to hear it works now :)
