### ISSUE TITLE
Background thread rendering

### ISSUE THREAD

**Issue by AliMunchkin** [dmrschmidt/DSWaveformImage#5]
I wonder if this (awesome!) library could be modified so the waveform is generated on a background thread (then of course displayed on the main thread)? I've had a play dropping some of the processing onto a global queue but could not get it working.

I would love to use this in a DAW style app but require 'on the fly' updating of waveforms (recording functionality etc.). Doesn't matter if the waveforms take a little while to display, but cannot hold up the main thread to maintain UI responsiveness.

**Comment by AliMunchkin** [comment]
Thanks so much for picking this up and providing some example code, I really appreciate it :)

I hope to consider this for an upcoming project and let you know how I get on.

**Comment by dmrschmidt** [comment]
Sure thing! If you end up using it - or simply exploring it a bit - I appreciate every bit of feedback :) As the core of your original issue can be addressed and the README is now explaining it too, I’ll consider this closed for now. Will still get back to supporting this more out of the box at some
later point.
