### ISSUE TITLE
Error installing with SPM

### ISSUE THREAD

**Issue by hoangnam714** [dmrschmidt/DSWaveformImage#50]
<img width="665" alt="Screen Shot 2022-11-21 at 17 12 01" src="https://user-images.githubusercontent.com/51524705/203024186-bbd13958-a8b9-4e9b-bbc8-f32765c2afdc.png">
Cannot find type 'SCAudioManager' in scope 
I used SPM to install DSWaveformImage, but I can't find SCAudioManager
xcode Version 14.1 (14B47b), UIKit

**Comment by dmrschmidt** [comment]
Hey @hoangnam714,

that's correct. SCAudioManager is not part of the library and only referenced in the docs to show an example for live recording. Feel free to use it, the source code is in the example project: https://github.com/dmrschmidt/DSWaveformImage/blob/main/Example/DSWaveformImageExample-iOS/SCAudioManager.m

It's really old Objective-C though and you are very likely to have different requirements for your use case, so I would not recommend it. I can also not provide guidance for this class, as it is outside of the scope of the library. Feel free to use it as inspiration though.

**Comment by hoangnam714** [comment]
@dmrschmidt ops..., so that's it
Thanks for your feedback
