### ISSUE TITLE
vertex and width

### ISSUE THREAD

**Issue by ducduy20** [dmrschmidt/DSWaveformImage#54]
how to make the width fit the view when the audio has peak

**Comment by ducduy20** [comment]
I want to see the peak of the wave when the sound peaks with the point in the middle

**Comment by dmrschmidt** [comment]
Hey @ducduy20, do you maybe mean the height? For that, set the verticalScalingFactor to 0.5

if you really mean width, can you maybe draw how exactly you want it to behave?

**Comment by ducduy20** [comment]
thanks @dmrschmidt . I fixed it, now I'm using it for my recording app
