### ISSUE TITLE
Set progress of WaveformImageView

### ISSUE THREAD

**Issue by shuuja** [dmrschmidt/DSWaveformImage#56]
Hi I am using WaveformImageView to show waveform of my audio file, and i am using AvAudioPlayer to play the audio. how can i set progress of the waveform when the audio is playing?

guard let url = Bundle.main.url(forResource: "OriginalRecording", withExtension: "m4a") else {
            return
        }

        middleWaveformView.configuration = Waveform.Configuration(
            backgroundColor: .lightGray.withAlphaComponent(0.1),
            style: .striped(.init(color: UIColor.red, width: 2, spacing: 1)),
            verticalScalingFactor: 0.5
        )
        middleWaveformView.waveformAudioURL = url

**Comment by dmrschmidt** [comment]
Please check the example and related issue that is linked in the readme: https://github.com/dmrschmidt/DSWaveformImage#playback-progress-indication
