### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by cortnum** [dmrschmidt/DSWaveformImage#6]
Hi,

This is an otherwise amazing framework, however there is one big issue that is plauging me, which prevents us from using this in our app.

When I set a width for the waveform, it does not properly fill out the image. It is as if it just appends a bunch of "silence" for the extra width, until I hit a certain width, where it starts rendering correctly again until it once more appends "silence" when making the image bigger.

I have attached screenshots of widths 260 (which shows only silence), 264 (which is almost perfect) and 300 (which shows "appended silence").

<img width="354" alt="screenshot" src="https://user-images.githubusercontent.com/27769137/36482689-65594406-1714-11e8-9444-7616dbc0cd8a.png">

<img width="359" alt="screenshot" src="https://user-images.githubusercontent.com/27769137/36482702-6e8bf4b0-1714-11e8-8aca-58c6d8375e30.png">

<img width="352" alt="screenshot" src="https://user-images.githubusercontent.com/27769137/36482724-7772d24c-1714-11e8-8afa-f2c268966b4b.png">

Here is our code:
        
        AudioExporter.instance.exportSongToM4A(song: self.song!, completionHandler: { (success) in
            let waveformImageDrawer = WaveformImageDrawer()
            let waveformSize = CGSize(width: 264, height: sequenceHeight)
            let scale = UIScreen.main.scale

            DispatchQueue.main.async {
                print("export finished: \(success)")
                if success {
                    if let trackWaveformImage = waveformImageDrawer.waveformImage(fromAudioAt: self.song!.exportUrlM4A(),
                                                                                  size: waveformSize,
                                                                                  color: UIColor.white,
                                                                                  backgroundColor: UIColor.clear,
                                                                                  style: .filled,
                                                                                  position: .middle,
                                                                                  scale: scale) {
                        
                        DispatchQueue.main.async {
                            let trackWaveformImageView = UIImageView(frame: CGRect(origin: CGPoint(x: x, y: y), size: waveformSize))
                            trackWaveformImageView.image = trackWaveformImage
                            trackWaveformImageView.contentMode = .scaleToFill
                            
                            self.waveformViews.append(trackWaveformImageView)
                            self.sequenceScrollView.addSubview(trackWaveformImageView)
                            self.sequenceScrollView.bringSubview(toFront: self.scrubberImageView)
                        }
                    }
                } else {
                    //TODO: Nothing?
                }
            }
        })

Any help would be appreciated

Cheers,

/Mikkel

**Comment by dmrschmidt** [comment]
closed with #8 and #12
