### ISSUE TITLE
Waveform is changing every time I scroll my chat message's table view how to manage it ? 

### ISSUE THREAD

**Issue by darkcodes00** [dmrschmidt/DSWaveformImage#60]

**Comment by darkcodes00** [comment]
After assigning the URL of the audio file(Downloaded URL path) to waveformimageview. My table has multiple cells which have waveformimageview. When I scroll up or scroll down with multiple cell tables every cell's waveform is changing. despite of having already downloaded audio file.

**Comment by dmrschmidt** [comment]
Hey darkcodes00,

thanks for using the library and reporting your issue. I have a few clarifying questions:

* do you mean they „change“ after being completely scrolled out of view and then back in?
* what exactly do you mean by „change“? Do they just get re-drawn? Or do they literally *look* different?

Just some speculative thoughts at the end:

If they scroll out of view completely, then it would be expected that they have to be redrawn. That’s to do with how a UITableView works.

If they literally change how they look, that would - at first glance - sound like an application later bug. The same input file will always generate the exact same looking waveform. Unless the frame changes, which then causes the calculation to use different dimensions. Frame changes fyi also cause re-draws.

Generally speaking, it may be advisable in your case to approach the problem differently. If you are having multiple (how many?) waveforms inside a table view, you would inevitably run into the first problem. To avoid that, you can use [WaveformImageDrawer](https://github.com/dmrschmidt/DSWaveformImage#waveformimagedrawer---creates-a-uiimage-waveform-from-an-audio-file) directly. Pre-render all waveform images, cache them locally and show those inside your UITableView.

The self-drawing classes are optimized for ease of use, not performance.

**Comment by dmrschmidt** [comment]
Closing this for now since I didn't hear back. Feel free to re-open if there's still anything I can help with.
