### ISSUE TITLE
Dampening vs. damping

### ISSUE THREAD

**Issue by leberwurstsaft** [dmrschmidt/DSWaveformImage#64]
Hey,

I noticed today that we misspelt "damping" in our project. "Dampening" means "to make slightly wet" 💦
Quick search in the project revealed the same mistake here.

https://github.com/dmrschmidt/DSWaveformImage/blob/f46cf0626b5abcb6ed2eb47b554dd5e31ee18d35/Sources/DSWaveformImage/WaveformImageTypes.swift#L136

**Comment by dmrschmidt** [comment]
Oh my 🙈 Thanks for reporting this.

I'll make sure to deprecate this until next major release and replace it with correct spelling.
