### ISSUE TITLE
Left to right instead of right to left

### ISSUE THREAD

**Issue by alexrfan03** [dmrschmidt/DSWaveformImage#65]
Is there a way to add the ability to have the live wave form to go left to right instead of right to left?

**Comment by dmrschmidt** [comment]
Not currently, no. Shouldn’t be too difficult to add I suppose, but given that it’s straightforward to just apply a translation in SwiftUI that achieves basically the same, I’m not sure I’d add it to the core library.

**Comment by alexrfan03** [comment]
Thanks for the idea.
