### ISSUE TITLE
Compile error in Xcode 15 beta. 

### ISSUE THREAD

**Issue by CacereLucas** [dmrschmidt/DSWaveformImage#72]
Hi, 
I have a compile error in the Xcode 15 beta (this does not happen in Xcode 14.3). The error is in the WaveformImageType file on line 143 and it says "Stored properties cannot be marked unavailable with '@available'". I'm using the latest version of the package. 

Any idea of what it could be?

Thank you!

<img width="1423" alt="Captura de pantalla 2023-06-08 a las 14 30 25" src="https://github.com/dmrschmidt/DSWaveformImage/assets/86716816/d1d40e06-053c-4cc2-a592-0c13fe300fd3">

**Comment by dmrschmidt** [comment]
OK scratch that. I wrongly assumed you were on the latest version and I didn't double-check the code before.

This has in fact already been removed in [11.0.1](https://github.com/dmrschmidt/DSWaveformImage/releases/tag/11.0.1) or to be precise in https://github.com/dmrschmidt/DSWaveformImage/commit/89d937ed1b4845372068074ce27c20708cdd4101.

So you'll need to update to at least that version, ideally 13.0.1 though, which is the current version.

I also just confirmed that this compiles in Xcode 15 and runs on iOS 17 beta.
