### ISSUE TITLE
xcode 15 not support. Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by EssamSoft** [dmrschmidt/DSWaveformImage#77]

**Comment by dmrschmidt** [comment]
Hey @EssamSoft. Thanks for reporting an issue.

To make it easier for people to identify the potential causes, please make sure in the future to provide at least a little bit of context. That could be - especially in the case you reported or in cases of crashes - line numbers, logging outputs and steps to reproduce.

Without that context it is often very hard if not impossible to reproduce reported issues, so a maintainer won't be able to help you with your request.

In this case you are lucky right now, and I am confident you are just running on an old version.

Please update to [13.0.2](https://github.com/dmrschmidt/DSWaveformImage/releases/tag/13.0.2).
