### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by ShravaniNovo** [dmrschmidt/DSWaveformImage#79]
i am having an issues with package getting error like Stored properties cannot be marked unavailable with '@available'  after so many tried its showing solution like this "you generally do not have direct control over fixing it within the package code itself. Instead, you will need to wait for an update to the package that resolves the issue", can you guys  please fix this issue or suggest some solution on this that would more helpful.

**Comment by dmrschmidt** [comment]
Sorry I missed this. Can you please verify that you are on the latest version? 13.0.2 at the minimum - where that issue should have been fixed. 14.0.0 ideally (which might require very minor API usage changes on your end).

The issue should be fixed in both of those versions.

**Comment by ShravaniNovo** [comment]
Good Morning ,

Thank you so much for your help its now working fine!



Thanks & Regards:
Shravani Dongre
+91-8412953151 (M.)
www.novotrax.com
[cid:20f37fc8-0158-4cd4-8e58-e0d8bf74af56]

________________________________

**Comment by dmrschmidt** [comment]
Happy to hear :)
