### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by SimmaAulakh** [dmrschmidt/DSWaveformImage#80]
Getting this issue after updating to Xcode 15. Can you please correct and update it? 

Stored properties cannot be marked unavailable with '@available'
<img width="1500" alt="Screenshot 2023-10-17 at 7 55 10 PM" src="https://github.com/dmrschmidt/DSWaveformImage/assets/47571702/f6a0d12a-1a61-4d00-a91c-42fa3c68dda6">

**Comment by dmrschmidt** [comment]
Please update the library to 13.0.2 or 14.0.0.
