### ISSUE TITLE
WaveForm Flickering

### ISSUE THREAD

**Issue by ReimannSamuel** [dmrschmidt/DSWaveformImage#84]
Im using the Waveform in tablecell and it WaveForm is getting updated on every reload. Is there any way to overCome this issue

**Comment by dmrschmidt** [comment]
The first thing that I would suggest is to use [WaveformImageDrawer](https://github.com/dmrschmidt/DSWaveformImage/blob/main/Sources/DSWaveformImage/WaveformImageDrawer.swift) directly instead. WaveformImageView is designed to adapt to frame changes but not in an optimized way.

If you do want to keep using a view, I would suggest to adapt your own WaveformImageView. I assume `layoutSubviews` may be the culprit in your use case, so it could be adapted to whatever your situation requires.

**Comment by dmrschmidt** [comment]
Closing this for now as there is no plan to work on the UIKit variants unless necessary. If you do have further questions, feel free to re-open this issue or another one any time.
