### ISSUE TITLE
Extra argument position in call error in MacOS

### ISSUE THREAD

**Issue by CacereLucas** [dmrschmidt/DSWaveformImage#85]
Hi! I have recently added to a new project in MacOS and I have the error "Extra argument `position` in call error" inside the WaveformImageDrawer file.

<img width="727" alt="Captura de pantalla 2023-11-03 a las 12 42 02" src="https://github.com/dmrschmidt/DSWaveformImage/assets/86716816/00738e2c-4744-400f-a631-0b67b112d265">

I'm using this same version on iOS and there's no problem, only in this new project on MacOS.
Any idea?

Thanks!

**Comment by dmrschmidt** [comment]
Oops, my bad. I accidentally misses that place. Thanks for reporting this!

14.2.1 fixes the issue.
