### ISSUE TITLE
I need to show loader till complete image generating from audio URL.

### ISSUE THREAD

**Issue by software124** [dmrschmidt/DSWaveformImage#86]
let asset = AVURLAsset(url: url)
            let width = (SCREENWIDTH() * CGFloat(Double(CMTimeGetSeconds(asset.duration))))/self.vdoDur
            let x = (SCREENWIDTH() - 170)/2
            self.waveformImageView = WaveformImageView(frame: CGRect(x: x, y: 15, width: width, height: 20))
            self.waveformImageView.configuration = Waveform.Configuration(
                backgroundColor: .clear,
                style: .striped(.init(color: UIColor(red: 209/255.0, green: 209/255.0, blue: 209/255.0, alpha: 1), width: 5, spacing: 5)),
                verticalScalingFactor: 0.5
            )
            self.waveformImageView.waveformAudioURL = url
            
how can i know image is loaded via audio URL.
Can you help me find solution of this?

**Comment by dmrschmidt** [comment]
Hey @software124. For UIKit, this is not currently supported by `WaveformImageView`. It is supported in SwiftUI's  [`WaveformView`](https://github.com/dmrschmidt/DSWaveformImage#waveformimagedrawer---creates-a-uiimage-waveform-from-an-audio-file) (see last example there in the linked README).

Using SwiftUI would be my recommended approach.

If you cannot use SwiftUI, the best alternative is using standard `UIImageView`s in conjunction with [`WaveformImageDrawer`](https://github.com/dmrschmidt/DSWaveformImage#waveformimagedrawer---creates-a-uiimage-waveform-from-an-audio-file)

**Comment by software124** [comment]
Thank you @dmrschmidt.
