### ISSUE TITLE
Update version in cocoapod

### ISSUE THREAD

**Issue by tanlucvo** [dmrschmidt/DSWaveformImage#87]
Can you release new version in cocoapod pls, current ver in cocoapod is 6.1

**Comment by dmrschmidt** [comment]
Hey there,

given the future direction of the iOS / macOS / visionOS platforms as a whole with SwiftPM as the officially supported package manager, there will be no further support for any other 3rd party package manager like cocoa pods or carthage etc.

Typically you should be able to add SPM packages to your project and have them play ok alongside each other.

**Comment by tanlucvo** [comment]
Thanks you 🚀
