### ISSUE TITLE
crash in iOS 17

### ISSUE THREAD

**Issue by ReimannSamuel** [dmrschmidt/DSWaveformImage#88]
crash occurs in DSWaveformImage package in ios 17.

**Comment by dmrschmidt** [comment]
Hey @ReimannSamuel,

thanks for reporting this, but I need a little more context to look at this in any meaningful way.

First, which version of the library are you using? Please make sure it is [the most recent, v14.2.1](https://github.com/dmrschmidt/DSWaveformImage/releases/tag/14.2.1).

Once that is confirmed, can you provide a stack trace? And which exact version of iOS 17 are you running and on what device / simulator?

Appreciate your help.

**Comment by ReimannSamuel** [comment]
Thanks for the response @dmrschmidt ,
Im not using the pod , Im using the package dependencies.  Im running in iphone 12(iOS version - 17.1.0) . Can i replace the package dependencies with the latest pod?

**Comment by ReimannSamuel** [comment]
Thanks for your support @dmrschmidt ,
Version 13.0.2 is working fine in  iOS version - 17.1.0

**Comment by ReimannSamuel** [comment]
Is there any sample project for this? If yes pls share the github link . It will be more useful for u

**Comment by dmrschmidt** [comment]
There currently unfortunately is not, no. And I won't find any time in the near future to do so. I might add something eventually to the example project, but again, it'll be of limited use as UICollectionViews / UITableViews typically get complex in different ways in different apps. This part is also something quite far outside the scope / concerns of this library.

The API for generating the waveform images is [illustrated in the README](https://github.com/dmrschmidt/DSWaveformImage#waveformimagedrawer---creates-a-uiimage-waveform-from-an-audio-file) but that's the easy part.
