### ISSUE TITLE
Can't Run Example

### ISSUE THREAD

**Issue by AndyZuntz** [dmrschmidt/DSWaveformImage#91]
Hi there, 

Apologies if this not really an issues, but rather my own lack of understanding.

I have successfully forked DSWaveformimage and fetched it  into my Xcode IDE.  (v15.2)

I know I have done partially right, because I managed to show a waveform within my own contentview using 
" @State var audioURL = Bundle.main.url(forResource: "BlueSuedeShoes", withExtension: "mp3")!
            WaveformView(audioURL: audioURL) .... etc....  and I got a lovely waveform filling my screen!

![Screenshot 2024-01-14 at 15 53 39](https://github.com/dmrschmidt/DSWaveformImage/assets/89162079/da22b139-46f9-4c34-96d6-ae2faac10bb4)
5)

Obviously needing styling and more attention, but proving that I can make it work.

Imagine my gratitude and euphoria! 
            
I then thought I should move on to understand in depth using the full "DSWaveformImageExample"

So I opened a simulator and pressed the run button (sorry about all the details) and got confirmation that: "Build  succeeded"

I expected to see something on the simulator or in a preview as has happened with other Swift projects, but no matter how much I scout around I can find nothing.  Have searched google and GitHub for advice but no success. 

You can probably tell that I am starting out with Swift, so apologies if this is something really obvious that I am misunderstanding.

I tried to contact you, Dennis, on Twitter, but got the alert that you were not taking messages, so apologies for putting it here.

I would be most grateful if you could assist here or via twitter: @Andy_Zuntz

Many thanks in advance 

Andy

**Comment by dmrschmidt** [comment]
Hey Andy, thank you for your detailed description. It’s a lot more easy to help people, when they provide enough detail than the other way round :)

I’m not on my MacBook right now, so I can’t take a screenshot for illustration, but from how you’re describing the situation, it sounds like you may have selected the wrong target. Thats this „bar“ next to the run button. My assumption is, that it says „DSWaveformImage“ there. If you click on it, a pop up should open with more choices. One each for the iOS, macOS and visionOS examples.

you’ll have to select the one you want to run, and then the respective simulator (or the app itself on macOS obv) should open.

Hope this helps?

**Comment by AndyZuntz** [comment]
HI Dennis

That is fantastic and thank you for your very prompt and helpful answer. 

It is all working now and I can see how much effort you have put into coding such a clever demo of your wonderful library.  I am sure that will keep me busy for a while understanding how it all works.  

you see, I have returned to programming after about 30 years now that I have finished full-time work, so this challenge is about learning as well as creating!

That you again and a coffee is winging its way towards you as a thank you ....

**Comment by dmrschmidt** [comment]
That sounds exciting! I'll be happy to try and help you with any further questions. And thank you so much for your support, I really do appreciate it 🙏

I will close this issue here now, as the original question is resolved. Feel free to re-open it though if anything related comes up or open new ones for any other question and or concerns.
