### ISSUE TITLE
LTR Support

### ISSUE THREAD

**Issue by Amin-0-1** [dmrschmidt/DSWaveformImage#92]
Hello gugys, thans for the great work, I am Just wondering if the WaveformLiveView support movement from left to right, I've tried semantic content attribute, it doesn't work anyway,
thanks.

**Comment by dmrschmidt** [comment]
Hey @Amin-0-1, it currently does not, no.

Since the view is symmetrical, as workarounds I’d recommend to use a `.rotationEffect(180)` to rotate-flip the waveform or `.scaleEffect(x: -1, y: 1)` to mirror-flip it.

Would that work as a workaround?
