### ISSUE TITLE
unable to create wave view with audio server url

### ISSUE THREAD

**Issue by shabnamwos** [dmrschmidt/DSWaveformImage#94]
I won’t be able to find the solution for creating the audio wave view with the server URL.

**Comment by dmrschmidt** [comment]
Hey there. Yes, that’s correct. The library doesn’t do online loading. I didn’t want to make any assumptions on how people would handle their online assets or add a different layer of local caching, especially with the vide variety of clients people use.

you can see https://github.com/dmrschmidt/DSWaveformImage/issues/22 for basic raw URLSession usage examples. Of course you are free to do it any other way.
