### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by ShoaibiOS** [dmrschmidt/DSWaveformImage#95]
After updating this title issue occurred 
<img width="1204" alt="Screenshot 2024-02-25 at 17 48 54" src="https://github.com/dmrschmidt/DSWaveformImage/assets/88189627/e855c024-cc98-4ab3-a6a5-f12a30b256ba">

**Comment by dmrschmidt** [comment]
Can you please verify that you’re on the latest major version, which is 14?

**Comment by hiren-appaspect** [comment]
I am facing the same issue as Stored properties cannot be marked unavailable with '@available' @dmrschmidt 
![Screenshot 2024-03-11 at 12 10 24 PM](https://github.com/dmrschmidt/DSWaveformImage/assets/82509588/d0b96cfa-96ab-42c5-98d6-64557bcf2b10)

**Comment by dmrschmidt** [comment]
@hiren-appaspect can you please also verify that you’re on the latest major version?

This should fix that problem.

If the problem still persists please update the issue with the exact dot-version of the library you’re on as well as the Xcode version and iOS deployment target version you’re using.

**Comment by hiren-appaspect** [comment]
@dmrschmidt Working fine now, change the Deployment target to 15.1 and SDK version to 14.2.2
Thanks a lot.
